name: peloton2garmin
author: jdowning
description: Syncs Peloton workouts to Garmin
branding:
  icon: rotate-cw
  color: red
inputs:
  peloton_email:
    description: Peloton Email
    required: true
  peloton_password:
    description: Peloton Password
    required: true
  garmin_email:
    description: Garmin Email
    required: true
  garmin_password:
    description: Garmin Password
    required: true
  docker_tag:
    description: Docker Hub tag
    default: console-stable
  timezone:
    description: Timezone used
    default: US/Pacific
  workouts_to_download:
    description: How many workouts to download from Peloton
    default: 10
  enable_fit_format:
    description: Enable FIT file format
    default: true
  enable_json_format:
    description: Enable JSON file format
    default: true
  enable_tcx_format:
    description: Enable TCX file format
    default: true
  include_time_in_hr_zones:
    description: Include time in heart rate zones
    default: true
  include_time_in_power_zones:
    description: Include time in power zones
    default: true
  upload_to_garmin:
    description: Upload target file to Garmin
    default: true
  upload_format:
    description: File format to upload to Garmin
    default: fit
runs:
  using: composite
  steps:
    - name: setup dirs
      shell: bash
      run: mkdir -p output && mkdir -p working
    - name: populate config
      shell: bash
      run: |
        cat <<EOT > configuration.local.json 
        {
          "App": {
            "EnablePolling": false
          },
          "Format": {
            "Fit": ${{ inputs.enable_fit_format }},
            "Json": ${{ inputs.enable_json_format }},
            "Tcx": ${{ inputs.enable_tcx_format }},
            "SaveLocalCopy": false,
            "IncludeTimeInHRZones": ${{ inputs.include_time_in_hr_zones }},
            "IncludeTimeInPowerZones": ${{ inputs.include_time_in_power_zones }}
          },
          "Peloton": {
            "NumWorkoutsToDownload": ${{ inputs.workouts_to_download }}
          },
          "Garmin": {
            "Upload": ${{ inputs.upload_to_garmin }},
            "FormatToUpload": "${{ inputs.upload_format }}"
          },
          "Observability": {
            "Prometheus": {
              "Enabled": false
            },
            "Jaeger": {
              "Enabled": false
            },
            "Serilog": {
              "Using": [ "Serilog.Sinks.Console"],
              "MinimumLevel": "Information"
            }
          }
        }
        EOT
    - name: run p2g
      shell: bash
      run: |
        cat configuration.local.json &&
        docker run --init \
          --volume $(pwd)/configuration.local.json:/app/configuration.local.json \
          --volume $(pwd)/output:/app/output \
          --volume $(pwd)/working:/app/working \
          --env "TZ=${{ inputs.timezone }}" \
          --env "P2G_DEVELOPER__USERAGENT=GCM-iOS-5.7.2.1" \
          --env "P2G_PELOTON__EMAIL=${{ inputs.PELOTON_EMAIL }}" \
          --env "P2G_PELOTON__PASSWORD=${{ inputs.PELOTON_PASSWORD }}" \
          --env "P2G_GARMIN__EMAIL=${{ inputs.GARMIN_EMAIL }}" \
          --env "P2G_GARMIN__PASSWORD=${{ inputs.GARMIN_PASSWORD }}" \
          philosowaffle/peloton-to-garmin:${{ inputs.docker_tag }}
